SUPABASE_URL = "https://pjpktbizbyokmnqrlbep.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqcGt0Yml6Ynlva21ucXJsYmVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcxNjcwODAsImV4cCI6MjA5Mjc0MzA4MH0.K-Rsq3gUJjpm39oapACWqHHMf5Zyby3jOY3NCxXURU4"
